/*
 * This source file was generated by the Gradle 'init' task
 */
package com.checkmarx.checkmarxts;

import org.junit.Test;
import static org.junit.Assert.*;

public class Canary {
    @Test public void canary() {
        assertTrue(true);
    }
}
