/*
 * This source file was generated by the Gradle 'init' task
 */
package com.checkmarx.checkmarxts;

public class DownloadCxFlow {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new DownloadCxFlow().getGreeting());
    }
}
