name: Called Workflow - build
on: 
    workflow_call:
      outputs:
        success:
          description: set to true if the workflow has completed
          value: ${{ jobs.set-output.outputs.success_value }}
      inputs:
        tag:
          description: 'The version tag to use for stamping build artifacts and naming generated archives'
          required: true
          type: string
        prerelease:
          description: 'Set to true if published build is a prerelease'
          type: boolean
          required: true
    #   secrets:
    #     PACKAGE_USER:
    #       required: true
    #     PACKAGE_PAT:
    #       required: true
       
               
jobs:
  build-download-cxflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9
        with:
          distribution: 'corretto'
          java-version: '17'
         
      - name: Fetch Code @ tag ${{ inputs.tag }}
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
        with:
          ref: refs/tags/${{ inputs.tag }}

      - name: Execute build
        run: tools/download-cxflow/gradlew build

      - name: Test
        run: |
            ls -l tools/download-cxflow
            mkdir artifacts
            cp tools/download-cxflow/app/build/libs/app.jar artifacts/download-cxflow.jar
    
 

#   publish-release:
#     runs-on: ubuntu-latest
#     needs: [build-download-cxflow]
#     steps:

#       - name: Download manual
#         uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16
#         with:
#           name: manual

#       - name: Download release notes
#         uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16
#         with:
#           name: release-notes

#       - name: Download publication notes
#         uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16
#         with:
#           name: release.md

#       - name: Download build-environment zip
#         uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16
#         with:
#           name: build-environment-zip

#       - name: Download enhanced-cxflow-scaresolver-tarball
#         uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16
#         with:
#           name: enhanced-cxflow-scaresolver-tarball
      
#       - name: Rename documentation artifacts
#         run: |
#           mv _main.pdf cx-supply-chain-toolkit-manual-${{ inputs.tag }}.pdf
#           mv release_notes.pdf cx-supply-chain-toolkit-release-notes-${{ inputs.tag }}.pdf
        
      - name: Create GitHub Release
        id: create_release
        uses: ncipollo/release-action@2c591bcc8ecdcd2db72b97d6147f871fcd833ba5
        with:
          allowUpdates: true
          artifactErrorsFailBuild: true
          artifacts: artifacts/*.jar
          artifactContentType: application/zip
        #   bodyFile: release.md
          name: ${{ inputs.tag }}
          prerelease: ${{ inputs.prerelease }}
          replacesArtifacts: true
          tag: ${{ inputs.tag }}

#   artifact-cleanup:
#     runs-on: ubuntu-latest
#     needs: [publish-release]
#     steps:
#       - uses: geekyeggo/delete-artifact@24928e75e6e6590170563b8ddae9fac674508aa1
#         with:
#           name: |
#             enhanced-cxflow-scaresolver-tarball
#             build-environment-zip
#             release.md
#             release-notes
#             manual


#   set-output:
#     runs-on: ubuntu-latest
#     needs: [artifact-cleanup]
#     outputs:
#       success_value: ${{ steps.complete.outputs.success }}
#     steps:
#       - name: Set Output
#         id: complete
#         run: echo "success=true" >> "$GITHUB_OUTPUT"
      

         